### ISSUE TITLE
关卡设计方案

### ISSUE THREAD

**Issue by juffson** [juffson/akae#1]
1、关于门 （三维？二维做起来效果不好吧？把门换成其他的东西应该可以）

**Comment by UotaniSayo** [comment]
不是很明白你的意思，二维俯视视角RPG的门经常是这个样子
另外对于下方的门，还有一种方案是可以看到外墙，然后门就和上方的一样画出来
![01](https://user-images.githubusercontent.com/7285550/29932637-6707f00e-8ea7-11e7-8f47-e659f602f76e.PNG)
![02](https://user-images.githubusercontent.com/7285550/29932658-74aa4518-8ea7-11e7-9d09-e8915a8f7fee.PNG)
![03](https://user-images.githubusercontent.com/7285550/29932659-753c08a4-8ea7-11e7-9bac-3f837a580c3e.PNG)

**Comment by juffson** [comment]
我开始以为是左右的移动的，理解错了
